### ISSUE TITLE
Support for structs larger than 32 bytes?

### ISSUE THREAD

**Issue by john-terrell** [hashmismatch/packed_struct.rs#68]
Hi, when attempting to create a PackedStruct larger than 32 bytes, compilation fails with:

error[E0277]: the trait bound `[u8; 55]: ByteArray` is not satisfied
  --> src/class_b/extended_position_report.rs:19:10
   |
19 | #[derive(PackedStruct)]
   |          ^^^^^^^^^^^^ the trait `ByteArray` is not implemented for `[u8; 55]`
   | 
  ::: .../registry/src/github.com-1ecc6299db9ec823/packed_struct-0.5.0/src/packing.rs:13:22
   |
13 |     type ByteArray : ByteArray;
   |                      --------- required by this bound in `packed_struct::PackedStruct::ByteArray`
   |
   = help: the following implementations were found:
             <[u8; 0] as ByteArray>
             <[u8; 10] as ByteArray>
             <[u8; 11] as ByteArray>
             <[u8; 12] as ByteArray>
           and 29 others
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

Looking at the source, it appears that only 32 bytes are supported via:

bytes_type!(Bytes32, 32);

Is there any way to support structs larger than 32 bytes?    Is fixing this just simply the case of adding more calls to bytes_type!() macro with the sizes I need?

**Comment by rudib** [comment]
The `0.5.0` release has two feature flags to generate these larger types, up to 64 and 256 bytes: https://github.com/hashmismatch/packed_struct.rs/blob/master/packed_struct/Cargo.toml#L24-L25

It's behind a feature flag because then compilation times increase quite a bit. I'm really hoping that we get const generics soon so this can be dealt with without any sort of code generation.

If that doesn't help, then please help an example that reproduces your problem. There's a couple of scenarios where these traits are used.

**Comment by john-terrell** [comment]
Hi, yes...I just found those!   Sorry to spam you.
